---
- name: Generate client certificate
  command: ./easyrsa build-client-full {{ client_name }} nopass
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Create .ovpn file for the client
  template:
    src: client.ovpn.j2
    dest: "{{ client_output_dir }}/{{ client_name }}.ovpn"
