---
- name: Update APT package manager repositories cache
  apt:
    update_cache: yes

- name: Install OpenVPN
  apt:
    name: openvpn
    state: present

- name: Copy server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: restart openvpn

- name: Copy OpenVPN server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: restart openvpn