---
- name: Update APT package manager repositories cache
  apt:
    update_cache: yes

- name: Install OpenVPN and Easy-RSA
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - openvpn
    - easy-rsa

- name: Setup CA directory
  command: make-cadir /etc/openvpn/easy-rsa

- name: Build CA
  command: ./build-ca
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build Server Certificate
  command: ./build-key-server server
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Build Diffie-Hellman key
  command: ./build-dh
  args:
    chdir: /etc/openvpn/easy-rsa

- name: Copy OpenVPN server configuration
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  notify: restart openvpn

