---
- name: Update APT package manager repositories cache
  apt:
    update_cache: yes

- name: Install OpenVPN
  apt:
    name: "{{ openvpn_package_name }}"
    state: "{{ package_state }}"
  # conditions of when openvopn is not installed
  when: ansible_system == "Linux" and openvpn_package_name not in ansible_facts.packages


- name: Copy server configuration
  template:
    src: "{{ server_conf_template }}"
    dest: "{{ server_conf_destination }}"
  notify: restart openvpn
